# {{projectName | pascal-case}}

{{description}}

## Development

```bash
npm install
npm run dev
```

## Build

```bash
npm run build
npm run preview
```

## Generated by

[Forge](https://github.com/Cantara/Synthesis-Little-Brother) — KCP-native project scaffolding.
