# {{artifactId | pascal-case}}

{{description}}

## Build

```bash
mvn test
mvn package
```

## Generated by

[Forge](https://github.com/Cantara/Synthesis-Little-Brother) — KCP-native project scaffolding.
