# Standard {{serviceName}}

Generated by Forge with Company Standards.

## Getting Started

1. Build: `mvn clean install`
2. Run: `java -jar target/{{artifactId}}-0.0.1-SNAPSHOT.jar`

## Architectural Standards

Refer to `KNOWLEDGE.yaml` for guidelines on how to extend this project.
